// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjgtoCRaZ73ZfLz9rAxp0PrBt0QacgFA',
    appId: '1:714845339163:web:6f21d454af0dc2a69f82be',
    messagingSenderId: '714845339163',
    projectId: 'meri-mari',
    authDomain: 'meri-mari.firebaseapp.com',
    storageBucket: 'meri-mari.firebasestorage.app',
    measurementId: 'G-YNRLKZXDK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEPUhHDpjwZbZHvkL531tTdsD_PGxaSk',
    appId: '1:714845339163:android:f9e98320124cdae19f82be',
    messagingSenderId: '714845339163',
    projectId: 'meri-mari',
    storageBucket: 'meri-mari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0T074QPxf_IwuiQfYPWXhj5jOsbK5vM',
    appId: '1:714845339163:ios:abc3234f6b7c25799f82be',
    messagingSenderId: '714845339163',
    projectId: 'meri-mari',
    storageBucket: 'meri-mari.firebasestorage.app',
    iosBundleId: 'com.example.meriMari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0T074QPxf_IwuiQfYPWXhj5jOsbK5vM',
    appId: '1:714845339163:ios:abc3234f6b7c25799f82be',
    messagingSenderId: '714845339163',
    projectId: 'meri-mari',
    storageBucket: 'meri-mari.firebasestorage.app',
    iosBundleId: 'com.example.meriMari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSjgtoCRaZ73ZfLz9rAxp0PrBt0QacgFA',
    appId: '1:714845339163:web:312f0992cbd756829f82be',
    messagingSenderId: '714845339163',
    projectId: 'meri-mari',
    authDomain: 'meri-mari.firebaseapp.com',
    storageBucket: 'meri-mari.firebasestorage.app',
    measurementId: 'G-53DF5B3P5H',
  );
}
